# ulamalu wants to meet eigen-wheels and draw together an atlas

In [820]:
import re
import matplotlib.pyplot as plt
from matplotlib import cm
import numpy as np 
import random
import pandas as pd
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import image
import matplotlib.animation as animation
import warnings
warnings.filterwarnings("ignore")

In [821]:
def get_next_symbol_in_ulam_loop(S):
    if S%2==0:
        return int(S/2)
    else:
        return 3*S+1
     


In [822]:
def get_ulam_loop(S):
    k=0
    S_v=np.zeros(1,dtype='int')
    S_v[k]=S

    while S_v[k]!=1:
        
        
        S_v=np.append(S_v,get_next_symbol_in_ulam_loop(S_v[k]))
        k=k+1
        
    return k,S_v

In [823]:
k,S_v =get_ulam_loop(27)
S_v

array([  27,   82,   41,  124,   62,   31,   94,   47,  142,   71,  214,
        107,  322,  161,  484,  242,  121,  364,  182,   91,  274,  137,
        412,  206,  103,  310,  155,  466,  233,  700,  350,  175,  526,
        263,  790,  395, 1186,  593, 1780,  890,  445, 1336,  668,  334,
        167,  502,  251,  754,  377, 1132,  566,  283,  850,  425, 1276,
        638,  319,  958,  479, 1438,  719, 2158, 1079, 3238, 1619, 4858,
       2429, 7288, 3644, 1822,  911, 2734, 1367, 4102, 2051, 6154, 3077,
       9232, 4616, 2308, 1154,  577, 1732,  866,  433, 1300,  650,  325,
        976,  488,  244,  122,   61,  184,   92,   46,   23,   70,   35,
        106,   53,  160,   80,   40,   20,   10,    5,   16,    8,    4,
          2,    1])

In [824]:
k

111

# 19 digit numbers 
* Check WITH CAUTION the max iterations for 3333333333333333333 and 5555555555555555555. You see what happens? Overflow

* Check what happens if you add a condition to the get_ulam_loop function in the while loop to limit the number of iterations

* What can we learn from this about how is being computed?

In [825]:
import math

def get_num_digits(num):
    if num == 0:
        return -1
    return int(math.log10(abs(num))) + 1



In [826]:
num=1111111111111111111
get_num_digits(num)


19

In [827]:

maxit,S_v =get_ulam_loop(num)
maxit

342

In [828]:
maxit,S_v =get_ulam_loop(2222222222222222222)
maxit

397

In [829]:
#this breaks if you add a 3 at the end giving 19 digits (not only adding a 3 the program hangs,test it)
maxit,S_v =get_ulam_loop(333333333333333333)
maxit

304

In [830]:
maxit,S_v =get_ulam_loop(4444444444444444444)
maxit

398

In [831]:
#this takes a loooot of time if you change the 8 by  5 or other numbers(you should check) at the end giving 19 equal digits
maxit,S_v =get_ulam_loop(5555555555555555558)
maxit

471

In [832]:
num=6666666666666666666
maxit,S_v =get_ulam_loop(num)
maxit

342

In [833]:
get_num_digits(num)

19

In [834]:
maxit,S_v =get_ulam_loop(7777777777777777777)
maxit

371

In [835]:
maxit,S_v =get_ulam_loop(8888888888888888888)
maxit

399

In [836]:
maxit,S_v =get_ulam_loop(999999999999999999)
maxit

370

In [837]:
maxit,S_v =get_ulam_loop(999999999999999999+9999999999999)
maxit

303

# adding a limit to the loop so we see the overflow

In [838]:
def get_ulam_loop(S,MAX_IT):
    k=0
    S_v=np.zeros(1,dtype='int')
    S_v[k]=S

    while S_v[k]!=1:
        
        
        S_v=np.append(S_v,get_next_symbol_in_ulam_loop(S_v[k]))
        k=k+1
        if k>MAX_IT:
          return k,S_v
        
    return k,S_v

In [839]:
#check the overflow
MAX_IT=399
maxit,S_v =get_ulam_loop(3333333333333333333,MAX_IT)
S_v[1:1000]

array([-8446744073709551616, -4223372036854775808, -2111686018427387904,
       -1055843009213693952,  -527921504606846976,  -263960752303423488,
        -131980376151711744,   -65990188075855872,   -32995094037927936,
         -16497547018963968,    -8248773509481984,    -4124386754740992,
          -2062193377370496,    -1031096688685248,     -515548344342624,
           -257774172171312,     -128887086085656,      -64443543042828,
            -32221771521414,      -16110885760707,      -48332657282120,
            -24166328641060,      -12083164320530,       -6041582160265,
            -18124746480794,       -9062373240397,      -27187119721190,
            -13593559860595,      -40780679581784,      -20390339790892,
            -10195169895446,       -5097584947723,      -15292754843168,
             -7646377421584,       -3823188710792,       -1911594355396,
              -955797177698,        -477898588849,       -1433695766546,
              -716847883273,       -2150543649818, 

In [840]:
maxit,S_v =get_ulam_loop(5555555555555555555,MAX_IT)
S_v

array([ 5555555555555555555, -1780077407042884950,  -890038703521442432,
        -445019351760721216,  -222509675880360608,  -111254837940180304,
         -55627418970090152,   -27813709485045076,   -13906854742522538,
          -6953427371261269,   -20860282113783806,   -10430141056891904,
          -5215070528445952,    -2607535264222976,    -1303767632111488,
           -651883816055744,     -325941908027872,     -162970954013936,
            -81485477006968,      -40742738503484,      -20371369251742,
            -10185684625871,      -30557053877612,      -15278526938806,
             -7639263469403,      -22917790408208,      -11458895204104,
             -5729447602052,       -2864723801026,       -1432361900513,
             -4297085701538,       -2148542850769,       -6445628552306,
             -3222814276153,       -9668442828458,       -4834221414229,
            -14502664242686,       -7251332121343,      -21753996364028,
            -10876998182014,       -5438499091007, 

# adding another kind of condition in whe loop while abs(S_v[k])!=1

In [841]:
def get_ulam_loop(S,MAX_IT):
    k=0
    S_v=np.zeros(1,dtype='int')
    S_v[k]=S

    while abs(S_v[k])!=1:
        
        
        S_v=np.append(S_v,get_next_symbol_in_ulam_loop(S_v[k]))
        k=k+1
        if k>MAX_IT:
          return k,S_v
        
    return k,S_v

In [842]:
maxit,S_v =get_ulam_loop(5555555555555555555,347+25*3)
S_v

array([ 5555555555555555555, -1780077407042884950,  -890038703521442432,
        -445019351760721216,  -222509675880360608,  -111254837940180304,
         -55627418970090152,   -27813709485045076,   -13906854742522538,
          -6953427371261269,   -20860282113783806,   -10430141056891904,
          -5215070528445952,    -2607535264222976,    -1303767632111488,
           -651883816055744,     -325941908027872,     -162970954013936,
            -81485477006968,      -40742738503484,      -20371369251742,
            -10185684625871,      -30557053877612,      -15278526938806,
             -7639263469403,      -22917790408208,      -11458895204104,
             -5729447602052,       -2864723801026,       -1432361900513,
             -4297085701538,       -2148542850769,       -6445628552306,
             -3222814276153,       -9668442828458,       -4834221414229,
            -14502664242686,       -7251332121343,      -21753996364028,
            -10876998182014,       -5438499091007, 

# The -2 -1 loop is reached in 268 steps using the negative numbers risen from the overflow only for 3333333333333333333 and not for 5555555555555555555

In [843]:
#check the overflow
MAX_IT=269
maxit,S_v =get_ulam_loop(3333333333333333333,MAX_IT)
S_v

array([ 3333333333333333333, -8446744073709551616, -4223372036854775808,
       -2111686018427387904, -1055843009213693952,  -527921504606846976,
        -263960752303423488,  -131980376151711744,   -65990188075855872,
         -32995094037927936,   -16497547018963968,    -8248773509481984,
          -4124386754740992,    -2062193377370496,    -1031096688685248,
           -515548344342624,     -257774172171312,     -128887086085656,
            -64443543042828,      -32221771521414,      -16110885760707,
            -48332657282120,      -24166328641060,      -12083164320530,
             -6041582160265,      -18124746480794,       -9062373240397,
            -27187119721190,      -13593559860595,      -40780679581784,
            -20390339790892,      -10195169895446,       -5097584947723,
            -15292754843168,       -7646377421584,       -3823188710792,
             -1911594355396,        -955797177698,        -477898588849,
             -1433695766546,        -716847883273, 

In [844]:
maxit

268

In [845]:
maxit,S_v =get_ulam_loop(5555555555555555555,100000)
S_v

array([ 5555555555555555555, -1780077407042884950,  -890038703521442432,
       ...,                  -37,                 -110,
                        -55])

In [846]:
maxit

100001

# So I was curious about the negative loops and used google:

https://www.reddit.com/r/math/comments/4z1es3/collatz_iteration_on_negative_integers/


![](reddit_capture.png)

# adding the check for the other loops to the code

In [847]:
def get_ulam_loop(S,MAX_IT):
    k=0
    S_v=np.zeros(1,dtype='int')
    S_v[k]=S

    while (abs(S_v[k]!=1)&(S_v[k]!=-5)&(S_v[k]!=-17) ):
        
        
        S_v=np.append(S_v,get_next_symbol_in_ulam_loop(S_v[k]))
        k=k+1
        if k>MAX_IT:
          return k,S_v
        
    return k,S_v

In [848]:
MAX_IT=269
maxit,S_v =get_ulam_loop(3333333333333333333,MAX_IT)
S_v

array([ 3333333333333333333, -8446744073709551616, -4223372036854775808,
       -2111686018427387904, -1055843009213693952,  -527921504606846976,
        -263960752303423488,  -131980376151711744,   -65990188075855872,
         -32995094037927936,   -16497547018963968,    -8248773509481984,
          -4124386754740992,    -2062193377370496,    -1031096688685248,
           -515548344342624,     -257774172171312,     -128887086085656,
            -64443543042828,      -32221771521414,      -16110885760707,
            -48332657282120,      -24166328641060,      -12083164320530,
             -6041582160265,      -18124746480794,       -9062373240397,
            -27187119721190,      -13593559860595,      -40780679581784,
            -20390339790892,      -10195169895446,       -5097584947723,
            -15292754843168,       -7646377421584,       -3823188710792,
             -1911594355396,        -955797177698,        -477898588849,
             -1433695766546,        -716847883273, 

In [849]:
maxit,S_v =get_ulam_loop(5555555555555555555,1000)
S_v

array([ 5555555555555555555, -1780077407042884950,  -890038703521442432,
        -445019351760721216,  -222509675880360608,  -111254837940180304,
         -55627418970090152,   -27813709485045076,   -13906854742522538,
          -6953427371261269,   -20860282113783806,   -10430141056891904,
          -5215070528445952,    -2607535264222976,    -1303767632111488,
           -651883816055744,     -325941908027872,     -162970954013936,
            -81485477006968,      -40742738503484,      -20371369251742,
            -10185684625871,      -30557053877612,      -15278526938806,
             -7639263469403,      -22917790408208,      -11458895204104,
             -5729447602052,       -2864723801026,       -1432361900513,
             -4297085701538,       -2148542850769,       -6445628552306,
             -3222814276153,       -9668442828458,       -4834221414229,
            -14502664242686,       -7251332121343,      -21753996364028,
            -10876998182014,       -5438499091007, 

In [850]:
maxit

347